# Generated by Django 5.2.5 on 2025-08-26 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_type', models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus')], help_text='Type of travel (Flight, Train, Bus)', max_length=10)),
                ('source', models.CharField(choices=[('Delhi', 'Delhi'), ('Mumbai', 'Mumbai'), ('Bangalore', 'Bangalore'), ('Chennai', 'Chennai'), ('Kolkata', 'Kolkata'), ('Hyderabad', 'Hyderabad'), ('Pune', 'Pune'), ('Ahmedabad', 'Ahmedabad'), ('Surat', 'Surat'), ('Jaipur', 'Jaipur'), ('Lucknow', 'Lucknow'), ('Kanpur', 'Kanpur'), ('Nagpur', 'Nagpur'), ('Indore', 'Indore'), ('Thane', 'Thane'), ('Bhopal', 'Bhopal'), ('Visakhapatnam', 'Visakhapatnam'), ('Pimpri-Chinchwad', 'Pimpri-Chinchwad'), ('Patna', 'Patna'), ('Vadodara', 'Vadodara'), ('Ghaziabad', 'Ghaziabad'), ('Ludhiana', 'Ludhiana'), ('Agra', 'Agra'), ('Nashik', 'Nashik'), ('Faridabad', 'Faridabad'), ('Meerut', 'Meerut'), ('Rajkot', 'Rajkot'), ('Kalyan-Dombivli', 'Kalyan-Dombivli'), ('Vasai-Virar', 'Vasai-Virar'), ('Varanasi', 'Varanasi'), ('Srinagar', 'Srinagar'), ('Aurangabad', 'Aurangabad'), ('Dhanbad', 'Dhanbad'), ('Amritsar', 'Amritsar'), ('Navi Mumbai', 'Navi Mumbai'), ('Allahabad', 'Allahabad'), ('Howrah', 'Howrah'), ('Ranchi', 'Ranchi'), ('Gwalior', 'Gwalior'), ('Jabalpur', 'Jabalpur'), ('Coimbatore', 'Coimbatore'), ('Vijayawada', 'Vijayawada'), ('Jodhpur', 'Jodhpur'), ('Madurai', 'Madurai'), ('Raipur', 'Raipur'), ('Kota', 'Kota'), ('Chandigarh', 'Chandigarh'), ('Guwahati', 'Guwahati'), ('Solapur', 'Solapur'), ('Hubli-Dharwad', 'Hubli-Dharwad'), ('Bareilly', 'Bareilly'), ('Moradabad', 'Moradabad'), ('Mysore', 'Mysore'), ('Gurgaon', 'Gurgaon'), ('Aligarh', 'Aligarh'), ('Jalandhar', 'Jalandhar'), ('Tiruchirappalli', 'Tiruchirappalli'), ('Bhubaneswar', 'Bhubaneswar'), ('Salem', 'Salem'), ('Warangal', 'Warangal'), ('Mira-Bhayandar', 'Mira-Bhayandar'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Guntur', 'Guntur'), ('Bhiwandi', 'Bhiwandi'), ('Saharanpur', 'Saharanpur'), ('Gorakhpur', 'Gorakhpur'), ('Bikaner', 'Bikaner'), ('Amravati', 'Amravati'), ('Noida', 'Noida'), ('Jamshedpur', 'Jamshedpur'), ('Bhilai', 'Bhilai'), ('Cuttack', 'Cuttack'), ('Firozabad', 'Firozabad'), ('Kochi', 'Kochi'), ('Bhavnagar', 'Bhavnagar'), ('Dehradun', 'Dehradun'), ('Durgapur', 'Durgapur'), ('Asansol', 'Asansol'), ('Rourkela', 'Rourkela'), ('Nanded', 'Nanded'), ('Kolhapur', 'Kolhapur'), ('Ajmer', 'Ajmer'), ('Akola', 'Akola'), ('Gulbarga', 'Gulbarga'), ('Jamnagar', 'Jamnagar'), ('Ujjain', 'Ujjain'), ('Loni', 'Loni'), ('Siliguri', 'Siliguri'), ('Jhansi', 'Jhansi'), ('Ulhasnagar', 'Ulhasnagar'), ('Jammu', 'Jammu'), ('Sangli-Miraj & Kupwad', 'Sangli-Miraj & Kupwad'), ('Mangalore', 'Mangalore'), ('Erode', 'Erode'), ('Belgaum', 'Belgaum'), ('Ambattur', 'Ambattur'), ('Tirunelveli', 'Tirunelveli'), ('Malegaon', 'Malegaon'), ('Gaya', 'Gaya'), ('Jalgaon', 'Jalgaon'), ('Udaipur', 'Udaipur'), ('Maheshtala', 'Maheshtala')], help_text='Departure city', max_length=100)),
                ('destination', models.CharField(choices=[('Delhi', 'Delhi'), ('Mumbai', 'Mumbai'), ('Bangalore', 'Bangalore'), ('Chennai', 'Chennai'), ('Kolkata', 'Kolkata'), ('Hyderabad', 'Hyderabad'), ('Pune', 'Pune'), ('Ahmedabad', 'Ahmedabad'), ('Surat', 'Surat'), ('Jaipur', 'Jaipur'), ('Lucknow', 'Lucknow'), ('Kanpur', 'Kanpur'), ('Nagpur', 'Nagpur'), ('Indore', 'Indore'), ('Thane', 'Thane'), ('Bhopal', 'Bhopal'), ('Visakhapatnam', 'Visakhapatnam'), ('Pimpri-Chinchwad', 'Pimpri-Chinchwad'), ('Patna', 'Patna'), ('Vadodara', 'Vadodara'), ('Ghaziabad', 'Ghaziabad'), ('Ludhiana', 'Ludhiana'), ('Agra', 'Agra'), ('Nashik', 'Nashik'), ('Faridabad', 'Faridabad'), ('Meerut', 'Meerut'), ('Rajkot', 'Rajkot'), ('Kalyan-Dombivli', 'Kalyan-Dombivli'), ('Vasai-Virar', 'Vasai-Virar'), ('Varanasi', 'Varanasi'), ('Srinagar', 'Srinagar'), ('Aurangabad', 'Aurangabad'), ('Dhanbad', 'Dhanbad'), ('Amritsar', 'Amritsar'), ('Navi Mumbai', 'Navi Mumbai'), ('Allahabad', 'Allahabad'), ('Howrah', 'Howrah'), ('Ranchi', 'Ranchi'), ('Gwalior', 'Gwalior'), ('Jabalpur', 'Jabalpur'), ('Coimbatore', 'Coimbatore'), ('Vijayawada', 'Vijayawada'), ('Jodhpur', 'Jodhpur'), ('Madurai', 'Madurai'), ('Raipur', 'Raipur'), ('Kota', 'Kota'), ('Chandigarh', 'Chandigarh'), ('Guwahati', 'Guwahati'), ('Solapur', 'Solapur'), ('Hubli-Dharwad', 'Hubli-Dharwad'), ('Bareilly', 'Bareilly'), ('Moradabad', 'Moradabad'), ('Mysore', 'Mysore'), ('Gurgaon', 'Gurgaon'), ('Aligarh', 'Aligarh'), ('Jalandhar', 'Jalandhar'), ('Tiruchirappalli', 'Tiruchirappalli'), ('Bhubaneswar', 'Bhubaneswar'), ('Salem', 'Salem'), ('Warangal', 'Warangal'), ('Mira-Bhayandar', 'Mira-Bhayandar'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Guntur', 'Guntur'), ('Bhiwandi', 'Bhiwandi'), ('Saharanpur', 'Saharanpur'), ('Gorakhpur', 'Gorakhpur'), ('Bikaner', 'Bikaner'), ('Amravati', 'Amravati'), ('Noida', 'Noida'), ('Jamshedpur', 'Jamshedpur'), ('Bhilai', 'Bhilai'), ('Cuttack', 'Cuttack'), ('Firozabad', 'Firozabad'), ('Kochi', 'Kochi'), ('Bhavnagar', 'Bhavnagar'), ('Dehradun', 'Dehradun'), ('Durgapur', 'Durgapur'), ('Asansol', 'Asansol'), ('Rourkela', 'Rourkela'), ('Nanded', 'Nanded'), ('Kolhapur', 'Kolhapur'), ('Ajmer', 'Ajmer'), ('Akola', 'Akola'), ('Gulbarga', 'Gulbarga'), ('Jamnagar', 'Jamnagar'), ('Ujjain', 'Ujjain'), ('Loni', 'Loni'), ('Siliguri', 'Siliguri'), ('Jhansi', 'Jhansi'), ('Ulhasnagar', 'Ulhasnagar'), ('Jammu', 'Jammu'), ('Sangli-Miraj & Kupwad', 'Sangli-Miraj & Kupwad'), ('Mangalore', 'Mangalore'), ('Erode', 'Erode'), ('Belgaum', 'Belgaum'), ('Ambattur', 'Ambattur'), ('Tirunelveli', 'Tirunelveli'), ('Malegaon', 'Malegaon'), ('Gaya', 'Gaya'), ('Jalgaon', 'Jalgaon'), ('Udaipur', 'Udaipur'), ('Maheshtala', 'Maheshtala')], help_text='Arrival city', max_length=100)),
                ('departure_datetime', models.DateTimeField(help_text='Departure date and time')),
                ('arrival_datetime', models.DateTimeField(blank=True, help_text='Arrival date and time', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in Indian Rupees (₹)', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('total_seats', models.PositiveIntegerField(help_text='Total number of seats available', validators=[django.core.validators.MinValueValidator(1)])),
                ('available_seats', models.PositiveIntegerField(help_text='Number of seats currently available', validators=[django.core.validators.MinValueValidator(0)])),
                ('operator_name', models.CharField(blank=True, help_text='Name of the airline, railway, or bus operator', max_length=100)),
                ('service_number', models.CharField(blank=True, help_text='Flight number, train number, or bus service number', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional details about the service')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this travel option is currently bookable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Travel Option',
                'verbose_name_plural': 'Travel Options',
                'ordering': ['departure_datetime'],
                'indexes': [models.Index(fields=['source', 'destination'], name='travel_trav_source_ea197d_idx'), models.Index(fields=['departure_datetime'], name='travel_trav_departu_224e7a_idx'), models.Index(fields=['travel_type'], name='travel_trav_travel__d862a5_idx'), models.Index(fields=['is_active'], name='travel_trav_is_acti_f55e83_idx')],
            },
        ),
    ]
