"""
Constants file for Travel Karo application
Contains lists of Indian cities, travel types, etc.
"""

# Major Indian cities for travel routes
INDIAN_CITIES = [
    ('Delhi', 'Delhi'),
    ('Mumbai', 'Mumbai'),
    ('Bangalore', 'Bangalore'),
    ('Chennai', 'Chennai'),
    ('Kolkata', 'Kolkata'),
    ('Hyderabad', 'Hyderabad'),
    ('Pune', 'Pune'),
    ('Ahmedabad', 'Ahmedabad'),
    ('Surat', 'Surat'),
    ('Jaipur', 'Jaipur'),
    ('Lucknow', 'Lucknow'),
    ('Kanpur', 'Kanpur'),
    ('Nagpur', 'Nagpur'),
    ('Indore', 'Indore'),
    ('Thane', 'Thane'),
    ('Bhopal', 'Bhopal'),
    ('Visakhapatnam', 'Visakhapatnam'),
    ('Pimpri-Chinchwad', 'Pimpri-Chinchwad'),
    ('Patna', 'Patna'),
    ('Vadodara', 'Vadodara'),
    ('Ghaziabad', 'Ghaziabad'),
    ('Ludhiana', 'Ludhiana'),
    ('Agra', 'Agra'),
    ('Nashik', 'Nashik'),
    ('Faridabad', 'Faridabad'),
    ('Meerut', 'Meerut'),
    ('Rajkot', 'Rajkot'),
    ('Kalyan-Dombivli', 'Kalyan-Dombivli'),
    ('Vasai-Virar', 'Vasai-Virar'),
    ('Varanasi', 'Varanasi'),
    ('Srinagar', 'Srinagar'),
    ('Aurangabad', 'Aurangabad'),
    ('Dhanbad', 'Dhanbad'),
    ('Amritsar', 'Amritsar'),
    ('Navi Mumbai', 'Navi Mumbai'),
    ('Allahabad', 'Allahabad'),
    ('Howrah', 'Howrah'),
    ('Ranchi', 'Ranchi'),
    ('Gwalior', 'Gwalior'),
    ('Jabalpur', 'Jabalpur'),
    ('Coimbatore', 'Coimbatore'),
    ('Vijayawada', 'Vijayawada'),
    ('Jodhpur', 'Jodhpur'),
    ('Madurai', 'Madurai'),
    ('Raipur', 'Raipur'),
    ('Kota', 'Kota'),
    ('Chandigarh', 'Chandigarh'),
    ('Guwahati', 'Guwahati'),
    ('Solapur', 'Solapur'),
    ('Hubli-Dharwad', 'Hubli-Dharwad'),
    ('Bareilly', 'Bareilly'),
    ('Moradabad', 'Moradabad'),
    ('Mysore', 'Mysore'),
    ('Gurgaon', 'Gurgaon'),
    ('Aligarh', 'Aligarh'),
    ('Jalandhar', 'Jalandhar'),
    ('Tiruchirappalli', 'Tiruchirappalli'),
    ('Bhubaneswar', 'Bhubaneswar'),
    ('Salem', 'Salem'),
    ('Warangal', 'Warangal'),
    ('Mira-Bhayandar', 'Mira-Bhayandar'),
    ('Thiruvananthapuram', 'Thiruvananthapuram'),
    ('Guntur', 'Guntur'),
    ('Bhiwandi', 'Bhiwandi'),
    ('Saharanpur', 'Saharanpur'),
    ('Gorakhpur', 'Gorakhpur'),
    ('Bikaner', 'Bikaner'),
    ('Amravati', 'Amravati'),
    ('Noida', 'Noida'),
    ('Jamshedpur', 'Jamshedpur'),
    ('Bhilai', 'Bhilai'),
    ('Cuttack', 'Cuttack'),
    ('Firozabad', 'Firozabad'),
    ('Kochi', 'Kochi'),
    ('Bhavnagar', 'Bhavnagar'),
    ('Dehradun', 'Dehradun'),
    ('Durgapur', 'Durgapur'),
    ('Asansol', 'Asansol'),
    ('Rourkela', 'Rourkela'),
    ('Nanded', 'Nanded'),
    ('Kolhapur', 'Kolhapur'),
    ('Ajmer', 'Ajmer'),
    ('Akola', 'Akola'),
    ('Gulbarga', 'Gulbarga'),
    ('Jamnagar', 'Jamnagar'),
    ('Ujjain', 'Ujjain'),
    ('Loni', 'Loni'),
    ('Siliguri', 'Siliguri'),
    ('Jhansi', 'Jhansi'),
    ('Ulhasnagar', 'Ulhasnagar'),
    ('Jammu', 'Jammu'),
    ('Sangli-Miraj & Kupwad', 'Sangli-Miraj & Kupwad'),
    ('Mangalore', 'Mangalore'),
    ('Erode', 'Erode'),
    ('Belgaum', 'Belgaum'),
    ('Ambattur', 'Ambattur'),
    ('Tirunelveli', 'Tirunelveli'),
    ('Malegaon', 'Malegaon'),
    ('Gaya', 'Gaya'),
    ('Jalgaon', 'Jalgaon'),
    ('Udaipur', 'Udaipur'),
    ('Maheshtala', 'Maheshtala'),
]

# Travel types
TRAVEL_TYPES = [
    ('flight', 'Flight'),
    ('train', 'Train'),
    ('bus', 'Bus'),
]

# Booking status choices
BOOKING_STATUS_CHOICES = [
    ('confirmed', 'Confirmed'),
    ('cancelled', 'Cancelled'),
    ('pending', 'Pending'),
]
