# Generated by Django 5.2.5 on 2025-08-26 11:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_seats', models.PositiveIntegerField(help_text='Number of seats booked', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price in Indian Rupees (₹)', max_digits=10)),
                ('booking_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when booking was made')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='confirmed', help_text='Current status of the booking', max_length=20)),
                ('passenger_details', models.JSONField(blank=True, default=dict, help_text='Additional passenger details in JSON format')),
                ('booking_reference', models.CharField(help_text='Unique booking reference number', max_length=20, unique=True)),
                ('contact_phone', models.CharField(help_text='Contact phone number for this booking', max_length=15)),
                ('contact_email', models.EmailField(help_text='Contact email for this booking', max_length=254)),
                ('special_requests', models.TextField(blank=True, help_text='Any special requests or notes for this booking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travel_option', models.ForeignKey(help_text='Travel option being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='travel.traveloption')),
                ('user', models.ForeignKey(help_text='User who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-booking_date'],
                'indexes': [models.Index(fields=['user', 'status'], name='bookings_bo_user_id_69a5d5_idx'), models.Index(fields=['booking_reference'], name='bookings_bo_booking_8a7545_idx'), models.Index(fields=['booking_date'], name='bookings_bo_booking_f34616_idx')],
            },
        ),
    ]
